## <b><font color ="red"> Numpy 기본문법

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install numpy -q -upgrade

Note: you may need to restart the kernel to use updated packages.



Usage:   
  C:\Users\User\anaconda3\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  C:\Users\User\anaconda3\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  C:\Users\User\anaconda3\python.exe -m pip install [options] [-e] <vcs project url> ...
  C:\Users\User\anaconda3\python.exe -m pip install [options] [-e] <local project path> ...
  C:\Users\User\anaconda3\python.exe -m pip install [options] <archive url/path> ...

no such option: -u


In [5]:
# Numpy 라이브러리 불러오기
import numpy as np  # Numpy를 np라는 이름으로 불러옵니다.

In [41]:
# 아래는 1차원 배열을 생성하는 코드입니다.
array = np.array([1, 2, 3, 4, 5])  # np.array()는 배열을 생성합니다.

In [21]:
# 1차원 배열 생성
array = np.array([1, 2, 3, 4, 5])  # 리스트를 사용해 배열 생성
print("1차원 배열:", array)

1차원 배열: [1 2 3 4 5]


In [43]:
# 배열의 자료형 확인
print("배열의 자료형:", array.dtype)  # 배열의 자료형을 출력


배열의 자료형: int32


In [25]:
# 2차원 배열 생성
matrix = np.array([[1, 2, 3], [4, 5, 6]])  # 2행 3열의 배열 생성
print("2차원 배열:\n", matrix)

2차원 배열:
 [[1 2 3]
 [4 5 6]]


In [13]:
# 배열의 크기 확인
print("배열의 크기:", matrix.size)  # 배열의 총 요소 개수
# 배열의 형태 확인
print("배열의 형태:", matrix.shape)  # 배열의 행과 열의 개수
# 배열의 차원 확인
print("배열의 차원:", matrix.ndim)  # 배열의 차원을 출력

배열의 크기: 6
배열의 형태: (2, 3)
배열의 차원: 2


In [14]:
# 배열의 합과 평균
print("배열의 합:", np.sum(matrix))      # 모든 요소의 합
print("배열의 평균:", np.mean(matrix))   # 모든 요소의 평균
# 배열의 최대값과 최소값
print("배열의 최대값:", np.max(matrix))  # 배열에서 가장 큰 값
print("배열의 최소값:", np.min(matrix))  # 배열에서 가장 작은 값
# 배열의 최대값과 최소값
print("배열의 최대값:", np.max(matrix))  # 배열에서 가장 큰 값
print("배열의 최소값:", np.min(matrix))  # 배열에서 가장 작은 값

배열의 합: 21
배열의 평균: 3.5
배열의 최대값: 6
배열의 최소값: 1
배열의 최대값: 6
배열의 최소값: 1


In [15]:
# 배열의 전치
transposed = matrix.T  # 행과 열을 바꿉니다.
print("전치된 배열:\n", transposed)


전치된 배열:
 [[1 4]
 [2 5]
 [3 6]]


## <b><font color ="red"> 판다스 기본문법

In [18]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [19]:
import pandas as pd

In [20]:
import pandas as pd

# Series 생성
data = [10, 20, 30, 40]
series = pd.Series(data)
print("Series:\n", series)

Series:
 0    10
1    20
2    30
3    40
dtype: int64


In [21]:
# 특정 값 참조
print("첫 번째 값:", series[0])  # 출력: 10

첫 번째 값: 10


In [23]:
# 딕셔너리를 사용해 DataFrame 생성
data = {
    "이름": ["김철수", "이영희", "박민수"],
    "수학": [85, 90, 78],
    "영어": [88, 84, 95]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
     이름  수학  영어
0  김철수  85  88
1  이영희  90  84
2  박민수  78  95


In [24]:
import pandas as pd

# 예제 데이터프레임 생성
data = {
    "이름": ["김철수", "이영희", "박민수"],
    "수학": [85, 90, 78],
    "영어": [88, 84, 95]
}
df = pd.DataFrame(data)

# (1) print()로 출력
print("print()로 출력:")
print(df)

# (2) DataFrame 형태로 출력 (인터랙티브 환경에서)
print("\nDataFrame 형태로 출력:")
df  # Jupyter Notebook에서는 df만 작성하면 표 형태로 출력


print()로 출력:
    이름  수학  영어
0  김철수  85  88
1  이영희  90  84
2  박민수  78  95

DataFrame 형태로 출력:


이름  수학  영어
0  김철수  85  88
1  이영희  90  84
2  박민수  78  95